apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-project-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-proj
spec:
  selector:
    matchLabels:
      app: postgres-proj
  template:
    metadata:
      labels:
        app: postgres-proj
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-project-pv-claim
      containers:
        - image: postgres
          name: postgres-proj
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-project-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-project-config
                  key: postgres_password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres-proj
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-proj
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres-proj